version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoicer-app
    hostname: invoicer-app
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/invoicer
      - BASE_URL=http://invoicer-app:3000
    networks:
      - invoicer-net
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - invoicer-net

networks:
  invoicer-net:
    driver: bridge

volumes:
  mongodb_data: 