version: '3'
services:
  invoicer:
    image: 339713064450.dkr.ecr.us-west-2.amazonaws.com/entropage/invoicer:latest
    network_mode: host
    environment:
      - MONGODB_URI=mongodb://localhost:27017/invoicer
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: