version: '3'
services:
  invoicer:
    image: invoicer:test
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/invoicer
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: